version: '3'
services:
  ctf:
    container_name: ctf
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASS=${EMAIL_PASS}
      - TEMP_POST_PASS=${TEMP_POST_PASS}
      - SUBS_EMAIL=${SUBS_EMAIL}
    restart: always
    build: .
    ports:
      - '3000:3000'
    restart: always
#     volumes: ['./:/var/www/html']
    environment:
      VIRTUAL_HOST: confessingthefaith.com, www.confessingthefaith.com
      LETSENCRYPT_HOST: confessingthefaith.com, www.confessingthefaith.com
      LETSENCRYPT_EMAIL: soriano@cbtseminary.org
networks:
  default:
    external:
      name: nginx-proxy