version: '3'
services:
  ctf:
    container_name: ctf
    restart: always
    build: .
    ports:
      - '3000:3000'
    # expose:
    #   - 443
    restart: always
#     volumes: ['./:/var/www/html']
    environment:
      VIRTUAL_HOST: confessingthefaith.com, www.confessingthefaith.com
      LETSENCRYPT_HOST: confessingthefaith.com, www.confessingthefaith.com
      LETSENCRYPT_EMAIL: soriano@cbtseminary.org
networks:
  default:
    external:
      name: nginx-proxy