version: '3'
services:
  mog:
    container_name: mog
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASS=${EMAIL_PASS}
      - TEMP_POST_PASS=${TEMP_POST_PASS}
      - SUBS_EMAIL=${SUBS_EMAIL}
    restart: always
    build: .
    ports:
      - '3001:3001'
    restart: always
#     volumes: ['./:/var/www/html']
    environment:
      VIRTUAL_HOST: manofgodnetwork.com, www.manofgodnetwork.com
      LETSENCRYPT_HOST: manofgodnetwork.com, www.manofgodnetwork.com
      LETSENCRYPT_EMAIL: soriano@cbtseminary.org
networks:
  default:
    external:
      name: nginx-proxy